import os
import sys
import argparse
from pathlib import Path
import textwrap

from scanner import ProjectScanner
from analyzer import ProjectAnalyzer

def format_readme_markdown(data) -> str:
    """將 Pydantic 模型轉為精美的 Markdown 文本"""
    md = textwrap.dedent(f"""\
    # {data.project_name} 🚀

    ## 🏗 Architecture & Logic
    {data.architecture}
    
    ### 🧮 Core Formula
    {data.logic_formula}

    ## ⚡ Quick Start
    ```bash
    {data.quick_start}
    ```
    
    ---
    *Auto-generated by your friendly neighborhood Agentic README Generator.*
    """)
    return md

def main():
    parser = argparse.ArgumentParser(description="🤖 Agentic README Generator")
    parser.add_argument("--path", type=str, default=".", help="要掃描的目標專案資料夾路徑")
    parser.add_argument("--out", type=str, default="README.md", help="輸出的 README 檔名 (預設會在執行目錄下建立)")
    args = parser.parse_args()

    target_dir = Path(args.path).resolve()
    output_file = Path.cwd() / args.out

    print(f"🔍 [Phase 1] 開始掃描專案目錄: {target_dir}")
    
    analyzer = None
    try:
        # 準備 AI Analyzer (同時也抓取 API key)
        api_key = os.getenv("GEMINI_API_KEY")
        analyzer = ProjectAnalyzer(api_key=api_key)

        # 執行掃描邏輯
        scanner = ProjectScanner(str(target_dir))
        tree_str = scanner.generate_tree()
        files_content = scanner.get_core_files_content()
        
        print(f"✅ 目錄掃描完成！找到 {len(files_content)} 個關鍵檔案。")
        print(f"🧠 [Phase 2] 正在呼叫 AI 分析師分析代碼邏輯...")

        # 執行分析並取得結構化結果
        readme_schema = analyzer.analyze_and_generate(tree_str, files_content)
        
        # 轉換成 Markdown 寫入檔案
        final_md = format_readme_markdown(readme_schema)
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(final_md)

        print(f"🎉 成功！專業的 README 已生成於: {output_file}")

    except Exception as e:
        print("\n❌ 糟糕，程式執行過程發生致命錯誤！", file=sys.stderr)
        
        # 若 Analyzer 有成功實例化，則試著讓 AI 解釋錯誤
        if analyzer and hasattr(analyzer, 'model'):
            print("🤖 呼叫 AI 進行錯誤診斷中...", file=sys.stderr)
            ai_explanation = analyzer.get_ai_excuse(str(e))
            print(f"👉 錯誤分析報告: {ai_explanation}", file=sys.stderr)
        else:
            print(f"👉 本地排錯助手: 系統發生未預期錯誤，詳細資訊為『{str(e)}』。請檢查檔案權限、目錄結構或是網路連線狀態。", file=sys.stderr)
        
        sys.exit(1)

if __name__ == "__main__":
    main()
